"""real init

Revision ID: f1c19d20c3b8
Revises: 
Create Date: 2026-05-08 15:07:39.487222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1c19d20c3b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count_value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('global_counter')
    # ### end Alembic commands ###
